######################################################################
# Automatically generated by qmake (2.01a) ? 10 20 07:39:22 2012
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bgPNG.h
SOURCES += main.cpp bgPNG.cpp

QT = core network

CODECFORTR = utf-8

win32 {
 debug {
  CONFIG += console
 }
}
